#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_concert/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import argparse
import sys
import rospy
import rocon_master_info

##############################################################################
# Functions
##############################################################################


def parse_arguments():
    parser = argparse.ArgumentParser(description='View master information details.')
    myargs = rospy.myargv(argv=sys.argv)
    return parser.parse_args(args=myargs[1:])


##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    parse_arguments()
    rocon_master_info.main('master_info', 'Master Information')
