#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_tools/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import os
import rocon_python_comms
import rocon_std_msgs.msg as rocon_std_msgs
import rocon_std_msgs.srv as rocon_std_srvs
import rospy

##############################################################################
# Main
##############################################################################

spin_rate = None  # needs to be set after rospy.init_node() call


def spin_rate_request(req):
    resp = rocon_std_srvs.SpinRateResponse()

    if req.new_rate:  # we change the rate if needed
        spin_rate = req.new_rate
    resp.current_rate = spin_rate
    return resp


if __name__ == '__main__':
    rospy.init_node('connection_cache')
    spin_rate = rospy.Rate(1)
    conn_cache = rocon_python_comms.ConnectionCache()
    conn_update_rate = rospy.Service("~spin_rate", rocon_std_srvs.SpinRate, spin_rate_request)
    conn_list = rospy.Publisher("~list", rocon_std_msgs.ConnectionsList, latch=True, queue_size=1)  # uptodate full list
    conn_diff = rospy.Publisher("~diff", rocon_std_msgs.ConnectionsDiff, queue_size=1)  # differences only for faster parsing.

    rospy.logdebug("node[%s, %s] entering spin(), pid[%s]", rospy.core.get_caller_id(), rospy.core.get_node_uri(), os.getpid())
    try:
        while not rospy.core.is_shutdown():

            """
            Update function to call from a looping thread.
            """
            try:
                new_conns, lost_conns = conn_cache.update()
                changed = False

                diff_msg = rocon_std_msgs.ConnectionsDiff()
                list_msg = rocon_std_msgs.ConnectionsList()
                for ct in rocon_python_comms.connection_types_list:
                    if new_conns[ct] or lost_conns[ct]:  # something changed
                        changed = True
                        for c in new_conns[ct]:
                            rocon_python_comms.create_connection(c)
                            diff_msg.added.append(c.msg)
                        for c in new_conns[ct]:
                            rocon_python_comms.create_connection(c)
                            diff_msg.lost.append(c.msg)
                        for c in conn_cache.connections[ct]:
                            rocon_python_comms.create_connection(c)
                            list_msg.connections.append(c.msg)

                if changed:
                    print "NEW : {0}".format(new_conns)
                    print "LOST : {0}".format(lost_conns)

                    conn_diff.publish(diff_msg)  # new_conns, old_conns
                    conn_list.publish(list_msg)  # conn_cache.connections

            except rospy.ROSException:
                rospy.logerr("ROS Watcher : Connections list unavailable.")
            except rospy.ROSInterruptException:
                rospy.logerr("ROS Watcher : ros shutdown while looking for Connections .")

            spin_rate.sleep()

    except KeyboardInterrupt:
        rospy.logdebug("keyboard interrupt, shutting down")
        rospy.core.signal_shutdown('keyboard interrupt')

